### ISSUE TITLE
Explain how this line chooses the mask by using nonzeros()

### ISSUE THREAD

**Issue by waynewccheng** [waynewccheng/andrewcode#2]
https://github.com/waynewccheng/andrewcode/blob/7dbc76e456be9271343d88b7534ea26e85e4292e/AndrewMatlabDetail/TissueMeasurements/f_processdata_roi.m#L73-L74

**Comment by andrew-lamont** [comment]
I will update the comments in the function to explain this better, but to clarify:

When loading the mask(s) from the select_roi_circle and/or select_roi_donut functions, we create a "blank" zeros matrix the size of the entire image. We then write pixel data from the ROI into this zeros matrix only at the pixel locations from the ROI. 

In lines 73 & 74 , the zero values (black pixels) are removed, leaving us with only the data from the desired ROI. Since purely black pixels are typically never present in our images, there is little concern that the nonzeros function will remove any pixels within our ROI.

**Comment by waynewccheng** [comment]
Ok
